parameters:
  dependsOn: ''
  displayName: ''
  jobName: ''
  vmImage: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.displayName }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: 'extract-bundle.yml'
  - template: 'install-choco.yml'
    parameters:
      packages: 'miniconda3'
  - powershell: |
      $env:PATH = "C:\tools\miniconda3\Scripts;C:\tools\miniconda3;C:\tools\miniconda3\Library\bin;$env:PATH"
      echo "##vso[task.setvariable variable=PATH]$env:PATH"
      $env:LIB = "C:\tools\miniconda3\Library\lib;$env:LIB"
      echo "##vso[task.setvariable variable=LIB]$env:LIB"
      conda --version
      conda install python=3.6.7 pip=10.0.1
      python --version
      pip --version
      pip install -q -r tests\requirements.txt
      pytest --version
    displayName: 'Install pytest'
  - powershell: 'powershell -command "& { . ./scripts/windows/make.ps1; integration_test }"'
    displayName: 'Run pytest'
  - task: PublishTestResults@2
    inputs:
      searchFolder: '$(Build.SourcesDirectory)'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'integration_results.xml'
      failTaskOnFailedTests: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'integration_results.html'
      artifactName: ${{ parameters.jobName }}
